# Generated by Django 3.2.7 on 2022-01-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dispositivo', models.CharField(max_length=25)),
            ],
        ),
    ]
